### ISSUE TITLE
Investigate frameworks for UI implementation

### ISSUE THREAD

**Issue by jjhursey** [jjhursey/mtt-modern#11]
To help with the CSS and layout issues we could consider using something like [Bootstrap](http://getbootstrap.com/2.3.2/) to handle most of the CSS (particuarly cross-site) setup and layout. That might make the design more maintainable.

**Comment by nchrien** [comment]
Would you like me to start looking into Bootstrap? I don't have much else to do right now, anyway.

**Comment by tomslynch** [comment]
Hey Natalie, that would be very helpful. The only thing that may blow up is if it overrides any of the other library's css. More specifically, the show/hide css from [multi-select](http://loudev.com). Shouldn't be too much of an issue or too much of a pain to counter regardless. Thanks!

[Obligatory CSS gif](http://imgur.com/Q3cUg29)

**Comment by jjhursey** [comment]
That sounds good. I think using something like Bootstrap to structure the page would be good since it would provide a slightly more consistent layout and better cross-browser support.

**Comment by nchrien** [comment]
My aggregator has been resurrected to handle CI-generated comments, but
this is my second priority after that. I should start really getting into
this in maybe two weeks?

**Comment by jjhursey** [comment]
That sounds great. Thanks!
