### ISSUE TITLE
Longer running queries result in UI issues

### ISSUE THREAD

**Issue by jjhursey** [jjhursey/mtt-modern#12]
Try running a longer range query: 03/01/2014 to 04/01/2014.

Notice that after hitting submit there is no indicator that shows the user that the UI is waiting for the server to return. Probably need at least a message stating that it is waiting on the server.

When you drill down on say MPI Name there is a hesitation in the UI (as it is waiting on the server) where the user may think that they need to click on something else (or might very well click on something else). It should have some indicator that it is processing - maybe an overlay image, or hide the table, or something.

Try the following drill down using the date range from above:
 * Click: MPI Version - dev-1184-gbb22d26
 * Click: Hardware - x86_64
 * Click : Org - cisco
 * Empty the Hardware field and click on Summary
 * Notice that the table shows all of the original data for a while, then will refresh with the new data

**Comment by tomslynch** [comment]
Loading gif added with current timeout of 10 seconds. Table remains hidden during ajax call.
