### ISSUE TITLE
Drill Downs (Multiple)

### ISSUE THREAD

**Issue by jjhursey** [jjhursey/mtt-modern#2]
**As a user looking at the Summary view I should be able to click on any cell in body of the table (not a number from the aggregation columns) and it will refine the search to include that field.**

For example, if I click on the `x86_64` value in the `Hardware` column then the table should only show rows that contain that value. This is automatic when I click on the `x86_64`, so I do not need to click on the Summary button.

**As a user looking at the Summary view I should be able to click on any cell in the body of the table (not a number from the aggregation column) and it will refine the search to include that field. I should be able to continue clicking on other fields to further narrow down the search to the desired results.**

For example, if I click on the `x86_64` value in the `Hardware` column then the table should only show rows that contain that value. This is automatic when I click on the `x86_64`, so I do not need to click on the Summary button. Then I should be able to click on the `ompi-nightly-master` value in the `MPI name` column to further narrow down the to search with these two parameters. This is automatic when I click on the `ompi-nightly-master`, so I do not need to click on the Summary button.

**As a user looking at the Summary view I should be able to click on any cell in the body of the table under an aggregation column and it will refine the search to include all of the fields in that row (will focus on a single row).**

For example, if I click on the number `30` in the `Test Run` phase then the table should only display the one row where that value was clicked (adding all of the fields from the left hand side to the search parameters). This will take me to the `Test Run` Summary view of the table. This is automatic when I click on the `30`, so I do not need to click on the Summary button.

**Comment by tomslynch** [comment]
Need confirmation that drill down is working.
Example workflow:
Click Test Build (Pass:1618) -> click Test Run (Pass:606) -> click Test Run (Timed:1)

Bug: You can not try to drill down on the same selection. This will result in the table being destroyed and the start over button will not work - a refresh would be needed. 
Bug example workflow:
Click Test Build (Pass:1618) -> click Test Run (Pass:606) -> click Test Run (606)

Also - drill down on appropriate columns should be working now. (e.g. you can not drill down on np) and restricted trying to drill down on a '0' - left me know if that is an issue.

**Comment by tomslynch** [comment]
As for the first and second user story - I believe this functionality is present when clicking upon the 'toggle local filter' option. To clear the filter without clicking the Summary btn, you would need to go into the local filter mode and hit clear fields to reset all filters.

**Comment by jjhursey** [comment]
I tried the workflow (I assume you mean the Test Run with 1618, not the Test Build):
Click Test Run (Pass:1618) -> click Test Run (Pass:606) -> click Test Run (Timed:1)

But the final page focused on the Skip not Timed column. However, this is not a valid workflow since after clicking on the Test Run (Pass:606) you see all of the results for all of the columns instead of just the Pass column.

**Comment by jjhursey** [comment]
The 'toggle local filter' option seems like a developer feature that is getting in the way of usability. It would not occur to me to see different behavior when I click on a cell based upon the two states of the toggle. IIRC the local filter is just referring to the cache - is that correct?

Having an 'advanced' option to disable the cache or enable the cache would be useful when working on the performance study (to see how much benefit there is from the cache), but it is not something the user should have to worry about unless they are debugging something going wrong with the site.

Determining if the site using the local cache should be automatically determined by the site when a state is changed. If the data is available locally to satisfy the query then you can use the local cache, otherwise you will have to go to the server. Ultimately, the cache would be useful when drilling down into the data (on a non-aggregate field like 'MPI version'), and when removing columns (which would cause the data to aggregate further).

If the cache is getting in the way of the demo tomorrow then just always go to the server for the data. Then we will need to add back for the final version. Maybe file it as a separate ticket.

**Comment by tomslynch** [comment]
Since it is not a valid workflow - does the multiple drill down feature currently work enough for the demonstration? If not - what should it be displaying instead. I've been messing around with the old reporter to try to see what might be wrong on my version.

**Comment by tomslynch** [comment]
You're correct - it is just referring to the cache. I will see what I can do - I might be able to do a simple trick to have the filter working in a few minutes. However, the smart cache feature you are talking about it where it knows when to go to the server and when not to would not be possible in a few minutes. 

I'll try something quick and push it so you can look at the change. It may satisfy what you're looking for.

**Comment by jjhursey** [comment]
With the local filter set to 'green' the multiple drill downs seems fine.

**Comment by tomslynch** [comment]
Alright, it now filters the cache constantly based upon what the fields contain. I am going to add support for the extra fields that are added during phase change. I do not believe they currently have filter support at the moment.
