### ISSUE TITLE
Relative Time Range dropdown not working

### ISSUE THREAD

**Issue by jjhursey** [jjhursey/mtt-modern#6]
**As a user in either the Summary or Detail view I should be able to select a relative date range to search the data**

For example, if I choose ```past 2 days``` from the dropdown I expect the two date fields to change to two days from today (in the left date field) and today (in the right date field). This will overwrite any date choices currently set in those fields. I expect to manually click on the Summary or Details button after modifying this value.

**Comment by tomslynch** [comment]
Currently have a restriction in the JS file to prevent this from working correctly. The reason for this is to prevent making queries that are outside of the range that is provided with the dataset given for the prototype. I can remove this restriction if you wanted to show that section working - it just might have some effects on queries.

**Comment by jjhursey** [comment]
We should remove the hard coding. The default dates should span the past 24 hours.

During testing we can inform them of the restricted date range. But this will allow you to demonstrate that dropdown changing the calendar fields correctly.

**Comment by tomslynch** [comment]
Hard coded restriction removed. Does not appear to create any additional bugs at the moment.

**Comment by tomslynch** [comment]
Found a bug - looking into it now.

**Comment by tomslynch** [comment]
Fixed

**Comment by jjhursey** [comment]
This looks like it is mostly working, but I found an additional bug.

1. Change the start date to 04/01/2015, and end date to 04/02/2015
1. Click on Summary
1. Use the dropdown to go to 'today'.
1. **Bug:** The end date changes, but not the start date

**Comment by tomslynch** [comment]
Good catch! That was a hard problem to troubleshoot and fix. The set date would change, but only to 4/02/2015.
```
start.datepicker('option', 'maxDate', now );
```
The above code was added to start of the function setFields. The problem was - that when selecting the dates, the datepicker would restrict the start date from going past what the end date was just set to. This  would not override or reset automatically when issuing: ``` start.datepicker( 'setDate', now ); ``` before or after issuing ``` end.datepicker( 'setDate', now ); ```
