### ISSUE TITLE
Color Coding of Details Table

### ISSUE THREAD

**Issue by tomslynch** [jjhursey/mtt-modern#9]
Currently all stdout's are green. Make this depicted on pass(green) or fail(red).

**Comment by tomslynch** [comment]
stdout and stderr are now color coded correctly. This is currently done by looking for "Success" in the result_message field. If this is not found, stdout and stderr are both red. 

Do we want both of these fields to be color coded? Or just stdout during fails and stderr on successes?

**Comment by tomslynch** [comment]
Added "Passed" to green style

**Comment by jjhursey** [comment]
You should probably use the ```test_result``` field (so make sure that it is always requested from the server when asking for details). That will give you an integer value, below is how to decode that integer:

* 0 : Failed
* 1 : Pass
* 2 : Skipped
* 3 : Timed out

I'll file a bug for myself to see if I can add a ```test_result_str``` field that will do the integer to string translation for future revisions.

**Comment by tomslynch** [comment]
solved by checking on test_result field. 0 || 1 = green, 2 || 3 = red

**Comment by jjhursey** [comment]
Shouldn't that be:
* 0 : Failed = Red
* 1 : Pass = Green
* 2 : Skipped = Yellow
* 3 : Timed out = Orange

To match the original reporter?
